### ISSUE TITLE
Empty lines are marked as "Invalid Operations".

### ISSUE THREAD

**Issue by honklol** [EmeraldMike/catoscript#6]
## Empty lines are marked as "Invalid Operations".
Even weirder - nano on Ubuntu 20.04.2 says that the file has **8 lines**, meanwhile, CatoScript is saying that the file has **9 lines** and that the last line that "exists" is an "Invalid Operation".

**Comment by EmeraldMike** [comment]
Will note this for next Dev version. Best fix as for now is adding a comment at the end. @honklol

**Comment by honklol** [comment]
![image](https://user-images.githubusercontent.com/33390199/127784839-db638f99-ce9e-47c8-8abc-8fc34c1c6d1e.png)<br><br>
![image](https://user-images.githubusercontent.com/33390199/127784855-ca7a879c-ab6d-4356-8341-37f17877c9f6.png)
worked :|

**Comment by EmeraldMike** [comment]
Yeahh Dev0.0.4 will fix this

**Comment by EmeraldMike** [comment]
Fixed in Dev0.0.4
